name: Validate changes in PR
on:
  pull_request:
    branches:
      - main
jobs:
  nx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run NX checks
        run: |
          yarn nx format:check
          yarn nx affected --target lint --parallel 3
          yarn nx affected --target test --parallel 3 --ci --code-coverage
          yarn nx affected --target build --parallel 3
          yarn nx affected --target typecheck --parallel 3
